# Generated by Django 5.2.6 on 2025-09-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_mlmodel_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictioncompound",
            name="lelp",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
