# Generated by Django 5.2.6 on 2025-10-15 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_predictioncompound_lelp"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiteratureCompound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ic50", models.FloatField(blank=True, null=True)),
                ("lelp", models.FloatField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="literature_data",
                        to="api.compound",
                    ),
                ),
            ],
            options={
                "unique_together": {("compound", "reference")},
            },
        ),
    ]
