# Generated by Django 5.2.6 on 2025-10-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_literaturecompound"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="literaturecompound",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="literaturecompound",
            name="pic50",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="literaturecompound",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="literaturecompound",
            name="reference",
        ),
    ]
