# Generated by Django 5.2.6 on 2025-10-20 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_literaturecompound_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="literaturecompound",
            old_name="pic50",
            new_name="ic50val",
        ),
    ]
